import 'macro-css'
import type { Metadata } from 'next'
import { IBM_Plex_Mono } from 'next/font/google'
import Wrapper from './components/Wrapper/Wrapper'
import { Context } from './Context/Context'
import './globals.scss'
const myfont = IBM_Plex_Mono({
	subsets: ['latin'],
	weight: '500',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={myfont.className}>
				<Context>
					<Wrapper>{children}</Wrapper>
				</Context>
			</body>
		</html>
	)
}
